### PR TITLE
Imp: use gost bytes pool

### PR DESCRIPTION
**Pull request by AlexStocks**
**What this PR does**:

use gost bytes pool to reuse byte slices.

### CODE REVIEW

**Comment by wongoo** [comment]
This branch has conflicts that must be resolved.

**Comment by wongoo** [comment]
binary type is not used regularly, this pr will not improve performance for most situation.

**Comment by AlexStocks** [comment]
@wongoo can not agree with u. if binary is used, the performance is better. the array length is 6KiB which is not a little slice.

**Comment by wongoo** [comment]
@AlexStocks I wonder is there some place can also use the bytes pool, not just for binary type.

**Comment by AlexStocks** [comment]
@wongoo none. All those bytes are return to user without this binary func.

**Comment by wongoo** [comment]
LGTM

**Pull request merged**
